version: '2'
services:

  semantic-query-engine:
      image: shukla2009/scala
      container_name: query-processing-engine
      hostname: query-processing-engine
      restart: always
      network_mode: bridge
      environment:
        - CASSANDRA_HOST=CASSANDRA_HOST_VAL
        - VIRTUOSO_URL=VIRTUOSO_IP_VAL:1111
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - DEPLOYMENT_PATH_VAL/deploy-query-processing-engine/latest/:/tmp
      # log_opt:
      #   max-size: 2g
      command: /tmp/bin/query-processing-engine -Dconfig.file=/tmp/conf/stage-docker-lb-diwo.conf  -Dcustomized.question.json=/tmp/conf/CustomizedQuestions.json

# QUERY PROCESSING ENGINE
# docker run --name query-processing-engine \
# -v /home/deployment/data/deploy-query-processing-engine/latest/:/tmp \
# -v /etc/timezone:/etc/timezone:ro \
# -h query-processing-engine \
# --log-opt max-size=2g \
# -e "CASSANDRA_HOST=10.1.100.53" \
# -e "VIRTUOSO_URL=10.1.100.56:1111" \
# -d  shukla2009/scala /tmp/bin/query-processing-engine -Dconfig.file=/tmp/conf/stage-docker.conf  -Dcustomized.question.json=/tmp/conf/CustomizedQuestions.json
