version: '2'
services:

  strategy-builder:
      image: strategy-builder
      container_name: strategy-builder
      hostname: strategy-builder
      restart: always
      network_mode: bridge
      environment:
        - CASSANDRA_HOST=CASSANDRA_HOST_VAL
        - KAFKA_URL=KAFKA_URL_VAL
        - ZK_URL=ZK_URL_VAL
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - DEPLOYMENT_PATH_VAL/deploy-strategy-builder/latest/:/tmp
      ports:
        - 14042:4040
      external_links:
        - knowledge-base:KB
      # log_opt:
      #   max-size: 2g
      command: /tmp/bin/strategy-builder -Dconfig.file=/tmp/conf/stage-docker.conf

#STRATEGY BUILDER
# docker run --name strategy-builder \
# -h strategy-builder \
# -v /home/synerzip/data/jenkins/workspace/deploy-strategy-builder/latest/:/tmp \
# -v /etc/timezone:/etc/timezone:ro \
# --log-opt max-size=2g \
# --link knowledge-base:KB \
# -p 14040:4040 \
# -d shukla2009/scala /tmp/bin/strategy-builder -Dconfig.file=/tmp/conf/stage-docker.conf
