- name: pull scala image
  docker_image: name=shukla2009/scala
  tags:
    - pullscalaimage
    - createstrategybuilder

- name: copy Dockerfile to inventory machine
  copy: src=Dockerfile dest=/tmp/Dockerfile
  tags:
    - createstrategybuilder
    - copydockerfile-SB

- name: run Docker file to create strategy-builder image
  docker_image: path=/tmp name=strategy-builder state=present
  tags:
    - createstrategybuilder
    - buildstrategybuilderimage

- name: copy docker-compose file to inventory machine
  copy: src=docker-compose.yml dest=/tmp/dockercompose/strategy-builder/
  tags:
    - copydockercomposefile-SB
    - createstrategybuilder

- name: modify docker-compose file with env varaibles values
  shell: sed -i "s/CASSANDRA_HOST_VAL/{{CASSANDRA_HOST}}/g" /tmp/dockercompose/strategy-builder/docker-compose.yml \
         && sed -i "s/KAFKA_URL_VAL/{{KAFKA_URL}}/g" /tmp/dockercompose/strategy-builder/docker-compose.yml \
         && sed -i "s/ZK_URL_VAL/{{ZK_URL}}/g" /tmp/dockercompose/strategy-builder/docker-compose.yml \
         && sed -i "s/DEPLOYMENT_PATH_VAL/{{DEPLOYMENT_PATH}}/g" /tmp/dockercompose/strategy-builder/docker-compose.yml
  tags:
    - modifydockercomposefile-SB
    - createstrategybuilder

- name: create and configure strategy-builder container
  docker_service: project_src=/tmp/dockercompose/strategy-builder/
  tags:
    - createstrategybuilder

