- name: pull scala image
  docker_image: name=shukla2009/scala
  tags:
    - pullscalaimage
    - creatediworestLB

- name: copy docker-compose file to inventory machine
  copy: src=docker-compose.yml dest=/tmp/dockercompose/diwo-rest-LB/
  tags:
    - copydockercomposefile-rest-LB
    - creatediworestLB

- name: modify docker-compose file with env varaibles values
  shell: sed -i "s/DEPLOYMENT_PATH_VAL/{{DEPLOYMENT_PATH}}/g" /tmp/dockercompose/diwo-rest-LB/docker-compose.yml
  tags:
    - modifysockercomposefile-rest-LB
    - creatediworestLB

- name: create and configure diwo-rest-LB container
  docker_service: project_src=/tmp/dockercompose/diwo-rest-LB/
  tags:
    - creatediworestLB


