version: '2'
services:

  diwo-backend:
      image: shukla2009/scala
      container_name: diwo-backend
      hostname: diwo-backend
      restart: always
      network_mode: bridge
      environment:
        - CASSANDRA_HOST=CASSANDRA_HOST_VAL
        - KAFKA_URL=KAFKA_URL_VAL
        - ZK_URL=ZK_URL_VAL
      volumes:
        - /etc/timezone:/etc/timezone:ro
        - DEPLOYMENT_PATH_VAL/deploy-diwo-backend/latest/:/tmp
      ports:
        - 14041:4040
      external_links:
        - knowledge-base:KB
      # log_opt:
      #   max-size: 2g
      command: /tmp/bin/diwo-backend -Dconfig.file=/tmp/conf/stage-docker.conf

#diwo-backend
# docker run --name diwo-backend \
# -v /home/synerzip/data/jenkins/workspace/deploy-diwo-backend/latest/:/tmp  \
# -v /etc/timezone:/etc/timezone:ro \
# -e "CASSANDRA_HOST=10.1.100.53" \
# --link knowledge-base:KB \
# -e "KAFKA_URL=10.1.100.56:9092"  \
# -e "ZK_URL=10.1.100.56:2181" \
# -p 14041:4040 \
# -d  shukla2009/scala /tmp/bin/diwo-backend -Dconfig.file=/tmp/conf/stage-docker.conf
