- name: pull scala image
  docker_image: name=shukla2009/scala
  tags:
    - pullscalaimage
    - creatediwobackend

- name: copy docker-compose file to inventory machine
  copy: src=docker-compose.yml dest=/tmp/dockercompose/diwo-backend/
  tags:
    - copydockercomposefile-backend
    - creatediwobackend

- name: modify docker-compose file with env varaibles values
  shell: sed -i "s/CASSANDRA_HOST_VAL/{{CASSANDRA_HOST}}/g" /tmp/dockercompose/diwo-backend/docker-compose.yml \
         && sed -i "s/KAFKA_URL_VAL/{{KAFKA_URL}}/g" /tmp/dockercompose/diwo-backend/docker-compose.yml \
         && sed -i "s/ZK_URL_VAL/{{ZK_URL}}/g" /tmp/dockercompose/diwo-backend/docker-compose.yml \
         && sed -i "s/DEPLOYMENT_PATH_VAL/{{DEPLOYMENT_PATH}}/g" /tmp/dockercompose/diwo-backend/docker-compose.yml
  tags:
    - creatediwobackend
    - modifydockercomposefile-backend

- name: create and configure diwo-backend container
  docker_service: project_src=/tmp/dockercompose/diwo-backend/
  tags:
    - creatediwobackend
