- name: pull zookeeper image
  docker_image: name=mesoscloud/zookeeper:3.4.8-ubuntu-14.04
  tags:
    - mesosCluster
    - pullzookeeperimage

- name: pull Mesos-master image
  docker_image: name=mesoscloud/mesos-master:0.28.1-ubuntu-14.04
  tags:
    - mesosCluster
    - pullmesosmasterimage

- name: pull Mesos-slave image
  docker_image: name=mesoscloud/mesos-slave:0.28.1-ubuntu-14.04
  tags:
    - linkmesoslave
    - pullmesosslaveimage

- name: copy Dockerfile 
  copy: src=Dockerfile dest=/tmp/Dockerfile
  tags:
    - linkmesoslave
    - copydockerfile

# Building an image to include spark inside mesos-slave from 'mesoscloud/mesos-master:0.28.1-ubuntu-14.04' image
- name: build and configure Mesos-slave image with spark
  docker_image: path=/tmp name=mesos-slave_2 tag=Spark2.0.2-Scala2.11 state=present
  tags:
    - linkmesoslave
    - buildmesoslavesparkimage

- name: create and configure zookeeper container
  docker_container:
    name: zookeeper_{{Zookeeper_ID}}
    image: mesoscloud/zookeeper
    hostname: zookeeper{{Zookeeper_ID}}
    network_mode: host
    restart_policy: on-failure
    restart_retries: 3
    env:
      MYID: "{{Zookeeper_ID}}"
      SERVERS: "{{SERVER1}},{{SERVER2}},{{SERVER3}}"
  tags:
    - mesosCluster
    - createzookeeper

- name: create and configure Mesos-Master container
  docker_container:
    name: mesos-master_{{Zookeeper_ID}}
    image: mesoscloud/mesos-master
    hostname: mesos-master{{Zookeeper_ID}}
    network_mode: host
    restart_policy: on-failure
    restart_retries: 3
    env:
      MESOS_HOSTNAME: "{{HOSTIP}}"
      MESOS_IP: "{{HOSTIP}}"
      MESOS_QUORUM: 2
      MESOS_ZK: "zk://{{SERVER1}}:2181,{{SERVER2}}:2181,{{SERVER3}}:2181/mesos"
#      MESOS_LOG_DIR: "/tmp/mesos"
#      SECRET: 123123
#      MESOS_AUTHENTICATE: false
#      MESOS_AUTHENTICATE_SLAVES: false
#      MESOS_CREDENTIALS: "/tmp/credentials"
  tags:
    - mesosCluster
    - createmesosmaster

- name: create and configure Mesos-slave container
  docker_container:
    name: mesos-slave_{{Zookeeper_ID}}
    image: mesos-slave_2:Spark2.0.2-Scala2.11
    hostname: mesos-slave_{{Zookeeper_ID}}
    network_mode: host
    restart_policy: on-failure
    restart_retries: 3
    privileged: yes
    volumes: 
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    env: 
      MESOS_HOSTNAME: "{{HOSTIP}}"
      MESOS_IP: "{{HOSTIP}}"
      MESOS_MASTER: "zk://{{SERVER1}}:2181,{{SERVER2}}:2181,{{SERVER3}}:2181/mesos"
 #     MESOS_LOG_DIR: "/tmp/mesos"
 #     SECRET: 123123
 #     MESOS_CREDENTIAL: "/tmp/credential"
  tags:
    - linkmesoslave
    - createmesosslave






